### PR TITLE
Fix data race issue on copyFn when there are multiple containers or initContainers

### LINKED ISSUE #421: Data race issue during image copy with multiple containers
Hi,

We encountered errors when running Pods with multiple `initContainers` with different `imagePullPolicy` values, where the value of the latest would overwrite the preceding ones. This then causes possible erroneous check conditions in the `Mutate` function [here](https://github.com/estahn/k8s-image-swapper/blob/main/pkg/webhook/image_swapper.go#L210) :
```go
copyFn := func() {
    if p.registryClient.ImageExists(targetImage) && container.ImagePullPolicy != corev1.PullAlways {
        return
    }
   ...
```
The variable `container` that is used inside `copyFn` is overwritten at every iteration of [the loop](https://github.com/estahn/k8s-image-swapper/blob/main/pkg/webhook/image_swapper.go#L181) on `containers`/`initContainers` and when the [goroutine](https://github.com/estahn/k8s-image-swapper/blob/main/pkg/webhook/image_swapper.go#L253) (that runs `copyFn`) is eventually run, the value has (very likely) already changed because the following iterations have been computed first. The value in `container.ImagePullPolicy` then does not correspond to the image in `targetImage`, but rather to the image of the following/last `container`.

Erroneous checks in the condition may, for example, lead to repeatedly try to copy images that are already present on the target because the last `container` has a `pullPolicy` or `Always`.

This issue only applies to `delayed` and `immediate` modes where the image copy is done in background.

### PR DESCRIPTION
**Pull request by Caomoji**
Fixes #421 

Creates a new `ImageCopier` object with its own `imagePullPolicy` to avoid a data race on the `container` object.

This new object is dedicated to the image copy process as it was done before but with its own subcontext and abstracted from the core mutation webhook processing. 

A new configurable `imageCopyDeadline` parameter has been added alongside an implementation of timeout throughout the different steps of the image copy. Every function called as part of the copy has been updated to include context evaluation and support abortion in case of context timeout.

### CODE REVIEW

File: pkg/webhook/image_swapper.go [hunk 1]
```diff
@@ -204,48 +204,50 @@ func (p *ImageSwapper) Mutate(ctx context.Context, ar *kwhmodel.AdmissionReview,
 
 			targetImage := p.targetName(srcRef)
 
-			copyFn := func() {
-				// Avoid unnecessary copying by ending early. For images such as :latest we adhere to the
-				// image pull policy.
-				if p.registryClient.ImageExists(targetImage) && container.ImagePullPolicy != corev1.PullAlways {
-					return
+			copyFn := func(targetImage string, container corev1.Container) func() {
```
Comment (Izzette) [inline pkg/webhook/image_swapper.go:207]: While this may be a quick fix and work very well, wouldn't a cleaner solution be to have an object for each "ImageCopier" with a `.CopyFn()`.  This would avoid any confusion caused by mutating variables and their scope(s).

**Comment by estahn** [comment]
@Caomoji Thanks, much appreciated. Extracting the `ImageCopier` into its own thing was on my backlog somewhere :) ... Looking good.

**Comment by estahn** [comment]
@Caomoji Would you mind rebasing and solving the conflicts?

File: docs/configuration.md [hunk 2]
```diff
@@ -38,9 +38,14 @@ The option `imageSwapPolicy` (default: `exists`) defines the mutation strategy u
...
-* `immediate`: Submits the copy job to a process queue and waits for it to finish (deadline 8s).
-* `force`: Attempts to immediately copy the image (deadline 8s).
+* `immediate`: Submits the copy job to a process queue and waits for it to finish (deadline defined by `imageCopyDeadline`).
+* `force`: Attempts to immediately copy the image (deadline defined by `imageCopyDeadline`).
 
+## ImageCopyDeadline
+
+The option `imageCopyDeadline` (default: `8s`) defines the duration after which the image copy if aborted.
+
+This option only applies for `immediate` and `force` image copy strategies.
```
Comment (Izzette) [inline docs/configuration.md:48]: Isn't the default `8` really?  Since the parameter is an integer of seconds?  It might also be worth noting that a value of `0` will be treated as if no value was provided (although that's pretty normal for Go projects, the user may already expect this).

**Review by Izzette — APPROVED** [review]
LGTM

**Comment by estahn** [comment]
@Caomoji Let me know if you need help resolving the conflicts.

File: docs/configuration.md (hunk 2 above)
Comment (Caomoji) [reply docs/configuration.md:48]: Regarding parsing of this field, if an integer is passed then it will be interpreted as a duration expressed in nanoseconds, while if a string with a correct format (see https://pkg.go.dev/time#ParseDuration) is passed, then it's interpreted using that unit. For instance `8s` is effectively converted to a duration of 8 seconds, just as `8000000000` would be too. 
Please let me know if you think we should be more explicit about this in the documentation.

**Comment by Caomoji** [comment]
@estahn Sorry for the delay, I am monitoring this fix in one of our live environments to make sure it effectively works before rebasing here, but I will do so shortly :+1:, thank you!

**Comment by estahn** [comment]
@Caomoji All good, thanks so much for your efforts.

**Comment by Caomoji** [comment]
@estahn We discovered that the context passed in the `Mutate` function would get canceled quite rapidly, thus causing unexpected timeout behavior in `delayed` `imageCopyPolicy` mode, and unexpectedly short deadline in other modes. 
To avoid cancellation propagation, and as it seems no data from this parent context is really being used, we decided to create a new one without inheriting from any value from it. Please let us know if you think we should still keep some information from this context.

Besides, some updates were made on logs to adapt messages that were present on the main branch.

We will resolve conflicts that this update will cause with [this PR](https://github.com/estahn/k8s-image-swapper/pull/394), please do not hesitate to provide additional feedback on those changes that, we believe, would open the path to a more registry-agnostic approach while allowing authentication to source registries 🙏

**Comment by estahn** [comment]
@Caomoji A bit confused, are you saying this PR should not be merged?

File: pkg/webhook/image_swapper.go [hunk 3]
```diff
@@ -172,8 +178,7 @@ func (p *ImageSwapper) Mutate(ctx context.Context, ar *kwhmodel.AdmissionReview,
 		Str("name", pod.Name).
 		Logger()
 
-	lctx := logger.
-		WithContext(ctx)
+	lctx := logger.WithContext(context.Background())
```
Comment (Caomoji) [inline pkg/webhook/image_swapper.go:181]: @estahn Oh sorry, regarding the issue, what I meant is that we fixed the mentioned problem by creating a brand new context here, rather than inheriting from the one passed in the function (`ctx`). The PR should now work as expected. My question was about possible use we have of the parent context `ctx` that we might not be aware of. Do you see a reason to add this parent context as a value of the new child context we create here?

And regarding the other PR, as this one will generate a lot of conflicts when merged, we will take care of resolving them in our other PR, not saying we shouldn't merge this one PR, sorry for the confusion.

Comment (estahn) [reply pkg/webhook/image_swapper.go:181]: Gotcha. I don't think we need to worry about the context. Thanks for clarifying. 👍🏼

**Comment by Izzette** [comment]
🥳 🎊 Thanks for your help and support @estahn
